version: '3.8'

services:
  # Service Registry (Eureka Server)
  service-registry:
    build: ./service-registry/service-registry
    container_name: service-registry
    ports:
      - "8761:8761"
    networks:
      - car-app-network

  # API Gateway
  api-gateway:
    build: ./api-gateway/api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - service-registry
      - user-service
      - car-service
      - order-service
      - payment-service
      - notification-service
    networks:
      - car-app-network

  # User Service & Database
  mysql-user:
    image: mysql
    container_name: mysql-user
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: user_db
    ports:
      - "3310:3306"
    networks:
      - car-app-network
    volumes:
      - mysql-user-data:/var/lib/mysql

  user-service:
    build: ./user-service/user-service
    container_name: user-service
    ports:
      - "8081:8081"
    depends_on:
      - mysql-user
      - service-registry
    networks:
      - car-app-network

  # Car Service & Database
  mysql-car:
    image: mysql
    container_name: mysql-car
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: car_db
    ports:
      - "3311:3306"
    networks:
      - car-app-network
    volumes:
      - mysql-car-data:/var/lib/mysql

  car-service:
    build: ./car-service/car-service
    container_name: car-service
    ports:
      - "8082:8082"
    depends_on:
      - mysql-car
      - service-registry
    networks:
      - car-app-network

  # Order Service & Database
  mysql-order:
    image: mysql
    container_name: mysql-order
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: order_db
    ports:
      - "3312:3306"
    networks:
      - car-app-network
    volumes:
      - mysql-order-data:/var/lib/mysql

  order-service:
    build: ./order-service/order-service
    container_name: order-service
    ports:
      - "8083:8083"
    depends_on:
      - mysql-order
      - service-registry
    networks:
      - car-app-network

  # Payment Service & Database
  mysql-payment:
    image: mysql
    container_name: mysql-payment
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: payment_db
    ports:
      - "3313:3306"
    networks:
      - car-app-network
    volumes:
      - mysql-payment-data:/var/lib/mysql


  payment-service:
    build: ./payment-service/payment-service
    container_name: payment-service
    ports:
      - "8084:8084"
    depends_on:
      - mysql-payment
      - service-registry
    networks:
      - car-app-network

  # Notification Service (Using Feign Client)
  notification-service:
    build: ./notification-service/notification-service
    container_name: notification-service
    ports:
      - "8085:8085"
    depends_on:
      - service-registry
    networks:
      - car-app-network

  # Zipkin for Distributed Tracing
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - car-app-network

networks:
  car-app-network:
    driver: bridge

volumes:
  mysql-user-data:
  mysql-car-data:
  mysql-order-data:
  mysql-payment-data:
